In [1]:
!pip install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB 445.2 kB/s eta 0:01:28
   ---------------------------------------- 0.1/38.8 MB 660.6 kB/s eta 0:00:59
   ---------------------------------------- 0.2/38.8 MB 1.2 MB/s eta 0:00:33
   ---------------------------------------- 0.3/38.8 MB 1.5 MB/s eta 0:00:27
   ---------------------------------------- 0.4/38.8 MB 1.8 MB/s eta 0:00:22
    --------------------------------------- 0.7/38.8 MB 2.2 MB/s eta 0:00:18
   - -------------------------------------- 1.2/38.8 MB 3.3 MB/s eta 0:00:12
   - -------------------------------------- 1.8/38.8 MB 4.6 MB/s eta 0:00:09
   -- ------------------------------------- 2.5/38.8 MB 5.9 MB/s eta 0:00:07
   -- ------------------------------------- 2.8/38.8 MB 5.8 MB/s eta 0:00:07
   --- ------------------------------------ 3.5/38.8 MB 6.7 MB/s eta 0:00:06
   ---- -

In [3]:
import cv2
import numpy as np

In [5]:
def display(title, img):
    cv2.imshow(title, img)
    # Chờ một khoảng thời gian
    cv2.waitKey(0)
    # Đóng window
    cv2.destroyWindow(title)

In [2]:
import cv2

In [4]:
path= 'C:\\Users\\wwwkb\\OneDrive\\Desktop\\458548812_434784309612677_8960315865400473921_n.jpg'
img = cv2.imread(path)
print(img)

[[[116 101  82]
  [117 102  83]
  [113  98  79]
  ...
  [185 166 153]
  [188 169 156]
  [188 169 156]]

 [[124 109  90]
  [117 102  83]
  [114  99  80]
  ...
  [183 164 151]
  [186 167 154]
  [182 163 150]]

 [[118 103  84]
  [118 103  84]
  [120 105  86]
  ...
  [186 167 154]
  [188 169 156]
  [182 163 150]]

 ...

 [[ 91  75  62]
  [ 86  70  57]
  [ 97  81  68]
  ...
  [128 112  99]
  [127 111  98]
  [122 106  93]]

 [[103  87  74]
  [ 90  74  61]
  [ 94  78  65]
  ...
  [130 114 101]
  [128 112  99]
  [123 107  94]]

 [[105  89  76]
  [ 97  81  68]
  [ 99  83  70]
  ...
  [129 113 100]
  [127 111  98]
  [122 106  93]]]


In [6]:
# Lấy kích thước
print(img.shape)
x, y, z = img.shape
print(x)
print(y)
print(z)

(1365, 2048, 3)
1365
2048
3


In [8]:
cv2.imshow('Window', img)
# Chờ một khoảng thời gian
cv2.waitKey(10000)
# Đóng window
cv2.destroyWindow('Window')

In [ ]:
# Tách màu
b, g, r = cv2.split(img)
cv2.imshow('Window', img)
cv2.imshow('Red', r)
cv2.imshow('Green', g)
cv2.imshow('Blue', b)

# Chờ một khoảng thời gian
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()

In [ ]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imshow('Window', img)
cv2.imshow('gray_img', gray_img)
cv2.imshow('img_2', img_2)
cv2.waitKey(0)
# Đóng window
cv2.destroyAllWindows()